# Generated by Django 4.0.1 on 2022-01-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='Orign',
            new_name='orign',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Expir_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Name',
        ),
        migrations.AddField(
            model_name='product',
            name='expir_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='makeup.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
