# Generated by Django 4.0.1 on 2022-02-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0002_rename_name_brand_name_rename_orign_brand_orign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='field_name',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
    ]
