# Generated by Django 4.0.1 on 2022-02-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0003_product_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='field_name',
            field=models.ImageField(default='SOME STRING', upload_to='static/images/'),
        ),
    ]
