# Minimal Makefile for Sphinx documentation
SPHINXOPTS    = 
SPHINXBUILD   = sphinx-build
SOURCEDIR     = .
BUILDDIR      = ../build/docs

.PHONY: html

html:
	$(SPHINXBUILD) -b html $(SOURCEDIR) $(BUILDDIR)
