name: Build and Deploy Documentation

on:
  pull:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-autobuild django
        pip install -r requirements.txt

    - name: Build documentation
      run: |
        chmod +x build_docs.sh
        ./build_docs.sh

    - name: Upload built documentation
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: build/docs
